# Generated by Django 4.0.5 on 2022-06-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='body_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_af',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ar_dz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ast',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_az',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_be',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_bg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_bn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_br',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_bs',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ca',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_cs',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_cy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_da',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_dsb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_el',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_en_au',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_en_gb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_eo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_es',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_es_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_es_co',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_es_mx',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_es_ni',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_es_ve',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_et',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_eu',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_fa',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_fi',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_fr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_fy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ga',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_gd',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_gl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_he',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_hi',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_hr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_hsb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_hu',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_hy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ia',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ig',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ind',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_io',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_is',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_it',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ja',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ka',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_kab',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_kk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_km',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_kn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ko',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ky',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_lb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_lt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_lv',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_mk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ml',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_mn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_mr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ms',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_my',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_nb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ne',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_nl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_nn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_os',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_pa',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_pl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_pt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_pt_br',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ro',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_sk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_sl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_sq',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_sr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_sr_latn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_sv',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_sw',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ta',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_te',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_tg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_th',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_tk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_tt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_udm',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_uk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_ur',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_vi',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_zh_hans',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='title_zh_hant',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='body_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_af',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ar_dz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ast',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_az',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_be',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_bg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_bn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_br',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_bs',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ca',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_cs',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_cy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_da',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_dsb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_el',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_en_au',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_en_gb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_eo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_es',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_es_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_es_co',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_es_mx',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_es_ni',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_es_ve',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_et',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_eu',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_fa',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_fi',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_fr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_fy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ga',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_gd',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_gl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_he',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_hi',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_hr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_hsb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_hu',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_hy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ia',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ig',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ind',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_io',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_is',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_it',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ja',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ka',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_kab',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_kk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_km',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_kn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ko',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ky',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_lb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_lt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_lv',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_mk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ml',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_mn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_mr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ms',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_my',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_nb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ne',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_nl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_nn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_os',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_pa',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_pl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_pt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_pt_br',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ro',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_sk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_sl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_sq',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_sr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_sr_latn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_sv',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_sw',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ta',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_te',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_tg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_th',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_tk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_tt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_udm',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_uk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_ur',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_vi',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_zh_hans',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homecarouselmodel',
            name='title_zh_hant',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
