# Generated by Django 4.0.5 on 2022-06-18 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_reviewsmodel_delete_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reviewsmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reviewsmodel',
            name='parent',
        ),
        migrations.AddField(
            model_name='reviewsmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
