# Generated by Django 4.0.5 on 2022-06-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_reviewsmodel_email_remove_reviewsmodel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsmodel',
            old_name='text',
            new_name='commit_text',
        ),
    ]
