# Generated by Django 4.0.5 on 2022-06-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homearticlemodel_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsmodel',
            old_name='commit_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='homearticlemodel',
            name='author',
        ),
    ]
