# Generated by Django 4.0.5 on 2022-06-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homearticlemodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsmodel',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
