# Generated by Django 4.0.5 on 2022-06-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_reviewsmodel_date_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsmodel',
            name='date_add',
        ),
    ]
