# Generated by Django 4.0.5 on 2022-06-22 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_homearticlemodel_body_af_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homearticlemodel',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='homearticlemodel',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reviewsmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewsmodel',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
