# Generated by Django 4.0.5 on 2022-06-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_reviewsmodel_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsmodel',
            name='data',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
