# Generated by Django 4.0.5 on 2022-06-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homearticlemodel_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homearticlemodel',
            options={'ordering': ('created_date',)},
        ),
        migrations.AlterModelOptions(
            name='reviewsmodel',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterField(
            model_name='homearticlemodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
