# Generated by Django 4.0.5 on 2022-06-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homearticlemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homearticlemodel',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterModelOptions(
            name='reviewsmodel',
            options={'ordering': ('-date_created',)},
        ),
    ]
