# Generated by Django 4.0.5 on 2022-06-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_reviewsmodel_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsmodel',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
