# Generated by Django 4.0.5 on 2022-06-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homearticlemodel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeCarouselModel',
        ),
    ]
